import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/global/Navbar";
import LayoutFirstSection from "@/components/global/LayoutFirstSection";
import LayoutThirdSection from "@/components/global/LayoutThirdSection";
import StackPageHeader from "@/components/pages/stack/StackPageHeader";

export const metadata: Metadata = {
  title: "Istismar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f3f3f3] ">
        <div className="fixed !z-50 w-full">
          <Navbar />
        </div>
        <div className="pt-32">
          <StackPageHeader />
          <main className="container grid grid-cols-[24%_50%_24%] gap-4 pt-5">
            <div className="">
              <LayoutFirstSection />
            </div>
            <div className="">{children}</div>
            <div className="">
              <LayoutThirdSection />
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
